Unbundle libpg_query
ppvan/pg_query_vala pull request #2
Opened 2024-04-05 22:12 UTC by MrRoy

Hello,

I recently [packaged psequel for Gentoo](https://github.com/gentoo/guru/commit/3603f1f49eeda9b2d0b33e62d91128dbeb7d02b1) and thus included a [package for pg_query_vala](https://github.com/gentoo/guru/commit/f7b91103a5d41d31e4305c1d70d92c9b41aae4dd). I also [packaged libpg_query](https://github.com/gentoo/guru/commit/4435babc4209a9564bd88c180e4b0b0cfdc8bdc3) separately from pg_query_vala (version 5.1.0).

Presently, pg_query_vala installs the libpg_query `.a` and `.so` files.
In the case of Gentoo (and I'm assuming other distros) this prevented pg_query_vala from being installed at the same time as the libpg_query package due to these file conflicts.
This PR unbundles libpg_query from this project and now instead depends on it being installed separately.

I'm applying this patch on the Gentoo package for pg_query_vala and it works fine, though please let me know if it can be improved :)

2024-04-06 03:55 UTC, ppvan commented
I guess that's works, but pg_query not available on many distro.

This changes will affect psequel itself (because flatpak require every dependencies declared and download before build). But I guess that's on me

Maybe I'll remove this project, see #1

2024-04-06 04:03 UTC, ppvan requested changes

2024-04-06 04:03 UTC, ppvan commented on meson.build
> +libpg_query = cc.find_library('pg_query', has_headers: 'pg_query.h', required: true)
Make this optional

2024-04-14 16:50 UTC, MrRoy commented
Hi @ppvan, thanks for the review and sorry for answering so late.
I updated this PR to make the changes optional. From my tests this works fine, with and without libpg_query installed on the system.

2024-04-14 16:52 UTC, merged